# Generated by Django 5.2.7 on 2025-10-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('remaining_amount', models.FloatField(default=0.0)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('gold_item', models.CharField(blank=True, max_length=100, null=True)),
                ('gold_weight', models.FloatField(blank=True, null=True)),
                ('gold_purity', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.FloatField()),
                ('remaining_amount', models.FloatField(default=0.0)),
                ('next_installment_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_receipts', to='loans.loan')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipt', to='payments.payment')),
            ],
        ),
    ]
