# Generated by Django 5.2.7 on 2025-10-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('gold', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_type', models.CharField(default='months', max_length=20)),
                ('duration_value', models.IntegerField(default=12)),
                ('loan_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('gold_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.golditem')),
            ],
        ),
    ]
